### ISSUE TITLE
icmp not recognized as protocol?

### ISSUE THREAD

**Issue by aktau** [nfnty/vim-nftables#1]
It appears that `icmp` gets different highlighting than `udp` and `tcp` and suchlike. Is that on purpose?

I made a screenshot illustrating what I mean:

![screen shot 2015-06-27 at 23 19 55](https://cloud.githubusercontent.com/assets/189413/8393895/1434642c-1d23-11e5-8b03-37e778719dd1.png)

**Comment by nfnty** [comment]
Not on purpose. I didn't know of this use case and it's not documented in the man page.
