### ISSUE TITLE
/etc/nftables.conf nto recognized

### ISSUE THREAD

**Issue by bemeurer** [nfnty/vim-nftables#4]
On Gentoo the nftables configuration file defaults to `/etc/nftables.conf`, which this fails to identify as a nft file. Peharps a special rule should be added for matching files named like that?

**Comment by nfnty** [comment]
Thanks! Be aware though that nftables config files usually have a shebang in the form of `#!/usr/bin/nft -f`, which are detected already.

**Comment by bemeurer** [comment]
@nfnty Thanks for the fix! I should probably add that shebang to mine!
